### ISSUE TITLE
[FEATURE]  Adding a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by guranshdeol** [guranshdeol/Invoice-Generator#3]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The Repo lacks a CONTRIBUTING.md file.

### Proposed Solution

Adding a valid CONTRIBUTING.md file to make it easier for other folks to Contribute.

### Do you want to work on this issue?

No

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign.

**Comment by guranshdeol** [comment]
Sure 😊

Waiting for your PR....

ALSO consider starring this repo.
