### ISSUE TITLE
[BUG] Readme file needs Updation

### ISSUE THREAD

**Issue by guranshdeol** [guranshdeol/Invoice-Generator#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After PR #1 , some additional features were added into the project, such as Export to excel, which are not reflected back into the readme file.

### Expected Behavior

The Readme file needs to be up to date with latest features, Referring to the PR #1 , Update all the changes in the README file

**Comment by jude-san** [comment]
hey @guranshdeol can i be assigned to this task?

**Comment by guranshdeol** [comment]
Yes, sure
